baseURL = 'https://beg7.github.io/bar/'
languageCode = 'ru-RU'
title = 'Коктейли'

theme = 'diary'

[taxonomies]
  ingredient = 'ingredients'
  kind = "kinds"

[menu]
[[menu.main]]
  identifier = 'cocktails'
  name = 'Коктейли'
  pre = "<i class='fa fa-heart'></i>"
  url = '/cocktails/'
  weight = -120
[[menu.main]]
  identifier = 'ingredients'
  name = 'Ингредиенты'
  pre = "<i class='fa fa-road'></i>"
  url = '/ingredients/'
  weight = -110
[[menu.main]]
  name = 'Типы'
  pre = "<i class='fa fa-road'></i>"
  url = '/kinds/'
  weight = -100

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = true
        title = true
        image = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
